FROM cirrusci/flutter:2.0.1

WORKDIR /usr/src/app

COPY . .

RUN flutter clean && flutter pub get \
    && flutter build apk --release

RUN mkdir -p /usr/apk

RUN cp /usr/src/app/build/app/outputs/flutter-apk/app-release.apk /usr/apk/letsEat.apk